### ISSUE TITLE
Unable to run danger-rubocop with this action

### ISSUE THREAD

**Issue by qnm** [MeilCli/danger-action#3]
## Description
We use `danger-rubocop` which I'm installing using the `Gemfile` and this config:

```
      - uses: MeilCli/danger-action@v2
        with:
          plugins_file: 'Gemfile'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This installs `danger-rubocop` gem but fails on execution

```
Bundled gems are installed into `./vendor/bundle`
danger --dangerfile=Dangerfile --danger_id=danger-pr
/opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:70:in `method_missing':  (Danger::DSLError)
[!] Invalid `Dangerfile` file: undefined local variable or method `rubocop' for #<Danger::Dangerfile:0x000055f8094980e8>
 #  from Dangerfile:6
 #  -------------------------------------------
 #  
 >  rubocop.lint({:force_exclusion => true})
 #  
 #  -------------------------------------------
```

I suspect running using `bundle exec` will solve this issue but I am not 100% on that.
