### ISSUE TITLE
Support .tools-versions to setup the danger version

### ISSUE THREAD

**Issue by danielgomezrico** [MeilCli/danger-action#552]
Hi

Current allows you to only setup like

```YAML
    - name: Check Lint and Code Style
      uses: MeilCli/danger-action@v5
      with:
         ...
        danger_version: 8.4.2
```

I would like to not put this version (`danger_version: 8.4.2`) in the YAML but define inside a file `.tool-versions` like:

```
danger 9.0.0
```

The thing is that with this you could just declare the action, and you will not need to override the value on each job.

## Feature description
This allows you to put danger in many flows without having to define the version for each one
